name: FineMapPipeline
channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - conda-forge::libgcc-ng=11.2.0
  - bioconda::bcftools=1.13
  - bioconda::plink2=2.00a2.3
  - bioconda::tabix=1.11
  - bioconda::htslib=1.13
  - conda-forge::gawk=5.0.1
  - conda-forge::coreutils=8.31
  - conda-forge::r-stringr=1.4.0
  - conda-forge::cairo=1.16.0
  - conda-forge::r-data.table=1.14.0
  - conda-forge::r-dplyr=1.0.7
  - conda-forge::r-ggplot2=3.3.5
  - conda-forge::r-optparse=1.6.6
  - conda-forge::r-patchwork=1.1.1
  - conda-forge::mscorefonts=0.0.1
  - conda-forge::r-rmarkdown=2.10
  - conda-forge::git=2.33.0
  - conda-forge::r-susier=0.11.42
  - conda-forge::r-r.utils=2.11.0
  - conda-forge::bgenix=1.1.7
